spring:
  output:
    ansi.enabled: always
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/db/voca
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
      open-in-view: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug